baseURL = 'https://kittenlover.dev/'
languageCode = 'en-us'
title = "Kittenlover's Rooftop"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    hl_Lines = ''
    hl_inline = false
    lineNoStart = 1
    noClasses = true
    style = 'algol_nu'
    tabWidth = 2
